Add tool
nlpsandbox/id-annotator-example pull request #5
Opened 2021-04-26 23:00 UTC by yy6linda

2021-04-27 16:51 UTC, yy6linda commented
@tschaffter This is ready for review.

2021-04-27 18:29 UTC, tschaffter requested changes
- Remove the folder server/openapi_server/test/lib
- Update the content of docker-compose.yml

2021-04-27 20:03 UTC, tschaffter requested changes

2021-04-27 20:03 UTC, tschaffter commented on server/openapi_server/__main__.py
> +    app.run(port=8080, debug=True)
```suggestion
    app.run(port=8080, debug=False)
```

2021-04-28 06:04 UTC, tschaffter approved these changes
This PR looks great! There just one typo that I will fix now before merging. Thanks! 🚀

2021-04-28 06:04 UTC, tschaffter commented on README.md
> +       git checkout -b upid-to-specification-x.y.z
```suggestion
       git checkout -b update-to-specification-x.y.z
```

2021-04-28 06:17 UTC, merged